### ISSUE TITLE
Missing some originality

### ISSUE THREAD

**Issue by arguiot** [FelixRilling/axon#4]
I know you’re trying to imitate Vue.js, but I think 🤔 you could push the concept of Vue.js a bit forward. I think it would be great 👍 if you could change the way of using aXon.js. To be honest with you, I had a similar concept (that you can definitely checkout 😊 [here](https://display.js.org)) and I pushed forward the concept. I wanted to have a structure that can immediately be recognized, and that’s what I’m trying to do now. I truly believe that you should do the same with your project 😊.

**Comment by RillingDev** [comment]
Hey,
I agree that taking a different approach than Vue might be very interesting, and I definitely plan to do exactly that, but probably under a different name/project. thanks for the feedback.
I took a look at your projects, which seems to have a rather unique approach as well, good luck with it!
